- name: Copy nomad volumes to client machines
  hosts: nomad_clients
  become: yes
  
  tasks:
  - name: Copy volumes.hcl to nomad clients
    copy:
      src: ../storage/volumes.hcl
      dest: /etc/nomad.d/volumes.hcl

  - name: Restart nomad
    service:
      name: nomad
      state: restarted